### ISSUE TITLE
Language bar not visible on mobile

### ISSUE THREAD

**Issue by nwpr** [simplesamlphp/simplesamlphp-assets-base#4]
The language bar doesn't slide in correctly on mobile devices. The actual menu items stay 11em outside of the screen.
I fixed it temporarily on our instance using this custom css:
```css
#layout.active #menu {
    margin-right: 0;
}
```
